local L = LibStub("AceLocale-3.0"):NewLocale("CatchwordAlert", "ruRU")
if not L then return end

L["Add Channel"] = "Добавить Канал"
L["Add catchword"] = "Добавить ключевое слово"
L["Add a channel to watch"] = "Добавить канал для просмотра"
L["Add a catchword to watch for"] = "Добавьте ключевое слово, за которым нужно следить"
L["Author"] = "Автор"
L["Channels"] = "Каналы"
L["Enable"] = "Включено"
L["Enable/disable the addon"] = "Включить/Отключить аддон"
L["catchword"] = "Ключевое Слово"
L["catchwords"] = "Ключевые Слова"
L["Message"] = "Сообщение"
L["CatchwordAlert"] = "CatchwordAlert"
L["Printed CatchwordAlert"] = "|cffd6266cCatchwordAlert |cFF00FF00<%s>"
L["Remove Channel"] = "Удалить канал"
L["Remove Keyword"] = "Удалить ключевое слово"
L["Remove selected channel from being watched"] = "Удалить выбранный канал из отслеживания"
L["Remove selected keyword from being watched for"] = "Удалить выбранное ключевое слово из списка отслеживаемых"
L["Select a channel to remove from being watched"] = "Выберите канал, чтобы удалить его из отслеживаемых"
L["Select a channel to watch"] = "Выберите канал для отслеживания"
L["Select a keyword to remove from being watched for"] = "Выберите ключевое слово, которое вы хотите удалить"
L["Select New Channel"] = "Выберите новый канал"
L["Sound"] = "Звук"
